# Data Manipulation

Lecture 2

Due by midnight after Lecture 3

<b>NetID:</b> SOLUTION

____

### Note(s): Please do not clear your results when you submit your notebook. It makes things a lot easier for us to grade if you include the output of your (code) cells below!

## Introduction to Pandas

Pandas is a primary data analysis library in Python. It offers a number of operations to aid in data exploration, cleaning and transformation, making it one of the most popular data science tools. To name a few examples of these operations, Pandas enables various methods to handle missing data and data pivoting, easy data sorting and description capabilities, fast generation of data plots, and Boolean indexing for fast image processing and other masking operations.

Some of the key features of Pandas are:
<ul>
<li>Ingestion and manipulation of heterogeneous data types
<li>Generating descriptive statistics on data to support exploration and communication
<li>Data cleaning using built in pandas functions
<li>Frequent data operations for subsetting, filtering, insertion, deletion and aggregation of data
<li>Merging and joining multiple datasets using dataframes
<li>Working with timestamps and time-series data
<li>Pandas also builds upon numpy and other Python packages to provide easy-to-use data structures and data manipulation functions with integrated indexing.
</ul>
**Additional Recommended Resources:**
<ul>
<li>Pandas Documentation
<li>Python for Data Analysis by Wes McKinney
<li>Python Data Science Handbook by Jake VanderPlas
</ul>

In [ ]:
import pandas as pd
import numpy as np

### Series
A Pandas `Series` is a one-dimensional `ndarray` (Remember what an `ndarray` is?). We can create a `series` simply by passing a list of values.

In [ ]:
first_series = pd.Series([10, 20, 30, 40])
print(first_series)

0    10
1    20
2    30
3    40
dtype: int64

The values don't necessarily need to be of integer type!

In [ ]:
second_series = pd.Series(['lorem', 'ipsum'])
print(second_series)

0    lorem
1    ipsum
dtype: object

### DataFrames
It's a two-dimensional tabular data structure in `Pandas` which helps in managing data in an orderly manner. The following are some key features of a  `Pandas DataFrame`:
<ul>
    <li>It has labelled axes
    <li>It's size is mutable
    <li>The columns may be of different datatypes
</ul>
An easy way to create a `DataFrame` is by passing a dictionary of objects.

In [ ]:
df = pd.DataFrame({
                    'col1': pd.Series([10, 20, 30]),
                    'col2': 'hello world',
                    'col3': pd.Timestamp('20180101')
                   })
df

   col1         col2       col3
0    10  hello world 2018-01-01
1    20  hello world 2018-01-01
2    30  hello world 2018-01-01

In [ ]:
multBy2=[x*2 for x in range(0,10)]
squared=[x**2 for x in range(0,10)]

df = pd.DataFrame({
                    'multiplyBy2': multBy2,
                    'squared': squared
                   })
df

   multiplyBy2  squared
0            0        0
1            2        1
2            4        4
3            6        9
4            8       16
5           10       25
6           12       36
7           14       49
8           16       64
9           18       81

## Playing with DataFrames
`DataFrames` can also be created from pre-saved tables! A very common format for saving such tables is the .csv (which stands for comma-separated values) format.

<b>Reading `DataFrames`</b>

In [ ]:
df=pd.read_csv('lecture2data.csv') #Titanic Dataset

##### A Quick Side Note
If you are interested in the dataset, or interested in exploring other datasets in your free time, here's where we got this datasets from: https://www.kaggle.com/c/titanic

Kaggle is a online community which actively uploads datasets, hosts data science competitions, and overall a beginner-friendly place to learn about data science. They also offer a no-setup, online Jupyter Notebook environment for you to play around with their datasets. You don't need to download or setup anything - just create an account, and start exploring!

If you're interested in seeing what an end-to-end data science project looks like, you can check out some of the data science projects other users have done on the datasets; just go to any dataset under "Datasets", click "Kernel", and you can follow along what other more experienced users have explored and posted on that dataset!

Back to the lecture material:

<b>Viewing `DataFrames`</b>

In [ ]:
# Check the columns in your dataframe
df.columns

Index(['PassengerId', 'Survived', 'Class', 'Name', 'Sex', 'Age', 'Ticket',
       'Fare', 'Cabin', 'Port'],
      dtype='object')

An excellent way to peek at the first/last few rows of your `DataFrame` is the `head()` and `tail()` functions. Let's try them out:

In [ ]:
df.head(3) #df.tail() to see last few rows

,PassengerId,Survived,Class,Name,Sex,Age,Ticket,Fare,Cabin,Port
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,A/5 21171,7.250,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,PC 17599,NaN,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,STON/O2. 3101282,7.925,NaN,S

In [ ]:
df['Age'].tail(5)#To get a specific column

886    27.0
887    19.0
888     NaN
889    26.0
890    32.0
Name: Age, dtype: float64

#### Filtering Dataframe

In [ ]:
# Filtering
FareAbove20_OlderThan40=df.loc[(df['Fare']>20) & (df['Age']>40)]
FareAbove20_OlderThan40.head(10)

,PassengerId,Survived,Class,Name,Sex,Age,Ticket,Fare,Cabin,Port
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,17463,51.8625,E46,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,113783,26.5500,C103,S
35,36,0,1,"Holverson, Mr. Alexander Oskar",male,42.0,113789,52.0000,NaN,S
52,53,1,1,"Harper, Mrs. Henry Sleeper (Myna Haxtun)",female,49.0,PC 17572,76.7292,D33,C
54,55,0,1,"Ostby, Mr. Engelhart Cornelius",male,65.0,113509,61.9792,B30,C
62,63,0,1,"Harris, Mr. Henry Birkhardt",male,45.0,36973,83.4750,C83,S
92,93,0,1,"Chaffee, Mr. Herbert Fuller",male,46.0,W.E.P. 5734,61.1750,E31,S
96,97,0,1,"Goldschmidt, Mr. George B",male,71.0,PC 17754,34.6542,A5,C
110,111,0,1,"Porter, Mr. Walter Chamberlain",male,47.0,110465,52.0000,C110,S
124,125,0,1,"White, Mr. Percival Wayland",male,54.0,35281,77.2875,D26,S

`.loc` is a useful function, but is often confused with `.iloc`. Check out this <a href="https://stackoverflow.com/questions/31593201/how-are-iloc-ix-and-loc-different">Stack Overflow Post</a> to clarify the concept.

#### Concatenating Dataframes

In [ ]:
df1 = pd.DataFrame({'A': ['A0', 'A1', 'A2', 'A3'],
                    'B': ['B0', 'B1', 'B2', 'B3'],
                    'C': ['C0', 'C1', 'C2', 'C3'],
                    'D': ['D0', 'D1', 'D2', 'D3']})
df1

    A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3

In [ ]:
df2 = pd.DataFrame({'A': ['A4', 'A5', 'A6', 'A7'],
                    'B': ['B4', 'B5', 'B6', 'B7'],
                    'C': ['C4', 'C5', 'C6', 'C7'],
                    'D': ['D4', 'D5', 'D6', 'D7']})
df2

    A   B   C   D
0  A4  B4  C4  D4
1  A5  B5  C5  D5
2  A6  B6  C6  D6
3  A7  B7  C7  D7

In [ ]:
pd.concat([df1,df2])

    A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3
0  A4  B4  C4  D4
1  A5  B5  C5  D5
2  A6  B6  C6  D6
3  A7  B7  C7  D7

<b>Summary Statistics</b>

We can check the statistics for individual columns by referring to the said column.

In [ ]:
df['Fare'].mean()

31.1646120667522

In [ ]:
df['Fare'].median()

14.4

In [ ]:
df['Cabin'].mode().iloc[0]

'B96 B98'

A much easier way to skim through the statistics for all the columns, however, is by using the `describe()` function.

In [ ]:
df.describe()

       PassengerId    Survived       Class         Age        Fare
count   891.000000  891.000000  891.000000  714.000000  779.000000
mean    446.000000    0.383838    2.308642   29.699118   31.164612
std     257.353842    0.486592    0.836071   14.526497   47.741674
min       1.000000    0.000000    1.000000    0.420000    0.000000
25%     223.500000    0.000000    2.000000   20.125000    7.895800
50%     446.000000    0.000000    3.000000   28.000000   14.400000
75%     668.500000    1.000000    3.000000   38.000000   30.035400
max     891.000000    1.000000    3.000000   80.000000  512.329200

## Problem 1 (2 points):
### Create a dataset, using the filtering technique, that includes only male survivors of the titanic and store it in a variable called 'male_survivors'. 1 is survived, 0 is not survived.

In [ ]:
male_survivors=df.loc[(df['Survived']==1) & (df['Sex']=='male')]
male_survivors.head(3)

,PassengerId,Survived,Class,Name,Sex,Age,Ticket,Fare,Cabin,Port
17,18,1,2,"Williams, Mr. Charles Eugene",male,NaN,244373,NaN,NaN,S
21,22,1,2,"Beesley, Mr. Lawrence",male,34.0,248698,13.0,D56,S
23,24,1,1,"Sloper, Mr. William Thompson",male,28.0,113788,35.5,A6,S

## Problem 2 (1 point):
### Determine the mean age of all these people and store them in a variable called 'mean_age_male_survivors'.

In [ ]:
mean_age_male_survivors=male_survivors['Age'].mean()
print(mean_age_male_survivors)

27.276021505376345

## Data Imputation

In [ ]:
df.head(4)

,PassengerId,Survived,Class,Name,Sex,Age,Ticket,Fare,Cabin,Port
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,A/5 21171,7.250,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,PC 17599,NaN,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,STON/O2. 3101282,7.925,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,113803,53.100,C123,S

In [ ]:
df['Cabin']=df['Cabin'].fillna('Top Deck')

In [ ]:
df.head(3)

,PassengerId,Survived,Class,Name,Sex,Age,Ticket,Fare,Cabin,Port
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,A/5 21171,7.250,Top Deck,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,PC 17599,NaN,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,STON/O2. 3101282,7.925,Top Deck,S

In [ ]:
#Dummy Encoding
df['male']=0
df['female']=0
for x in range(0,len(df)):
    if df['Sex'][x]=='male':
        df['male'][x]=1
    else:
        df['female'][x]=1

<ipython-input-23-bda140b899b1>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['male'][x]=1
<ipython-input-23-bda140b899b1>:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['female'][x]=1

In [ ]:
df

,PassengerId,Survived,Class,Name,Sex,Age,Ticket,Fare,Cabin,Port,male,female
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,A/5 21171,7.250,Top Deck,S,1,0
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,PC 17599,NaN,C85,C,0,1
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,STON/O2. 3101282,7.925,Top Deck,S,0,1
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,113803,53.100,C123,S,0,1
4,5,0,3,"Allen, Mr. William Henry",male,35.0,373450,8.050,Top Deck,S,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,211536,13.000,Top Deck,S,1,0
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,112053,30.000,B42,S,0,1
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,W./C. 6607,23.450,Top Deck,S,0,1
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,111369,NaN,C148,C,1,0
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,370376,7.750,Top Deck,Q,1,0

## Problem 3 (3 points)
### Impute the values that are NaN for the Fare column with the mean

In [ ]:
# mean=df['Fare'].mean()

In [ ]:
df['Fare']=df['Fare'].fillna(df['Fare'].mean())

NameError: name 'df' is not defined

In [ ]:
df.head(5)

,PassengerId,Survived,Class,Name,Sex,Age,Ticket,Fare,Cabin,Port,male,female
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,A/5 21171,7.250000,Top Deck,S,1,0
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,PC 17599,31.164612,C85,C,0,1
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,STON/O2. 3101282,7.925000,Top Deck,S,0,1
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,113803,53.100000,C123,S,0,1
4,5,0,3,"Allen, Mr. William Henry",male,35.0,373450,8.050000,Top Deck,S,1,0

### But WAIT!

How do you know what data to impute in any case? Here's a quick, high-level comparison of the different ways you can fill up missing data, along with their respective pros and cons: https://towardsdatascience.com/6-different-ways-to-compensate-for-missing-values-data-imputation-with-examples-6022d9ca0779

You can try implementing the first three examples on your free time - the materials covered in this lecture should give you enough information on how to implement them! The fourth example we will actually cover in a later class, but feel free to also explore the source code provided under the github links.

## Problem 4 (4 points)
### There are several rows with nan values for the age. First fill all the nan values with the mean age of the passengers. Then create a new dummy variable/column named 'child' to the dataframe and insert a 1 or a 0 in each row (1 for child/under_18, 0 for non-child/18_or_older).

In [ ]:
df['Age']=df['Age'].fillna(df['Age'].mean())

In [ ]:
# approach using where
# df['child']= df['Age'].where(df['Age'] < 18, other=1).astype(int)
# df['child'] = df['child'].where(~(df['Age'] < 18), other=0).astype(int)

# approach using loc
df.loc[df['Age'] < 18, 'child'] = 1
df.loc[~(df['Age'] < 18), 'child'] = 0
df['child'] = df['child'].astype(int)

In [ ]:
df.head(10)

,PassengerId,Survived,Class,Name,Sex,Age,Ticket,Fare,Cabin,Port,child
0,1,0,3,"Braund, Mr. Owen Harris",male,22.000000,A/5 21171,7.2500,NaN,S,1
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.000000,PC 17599,NaN,C85,C,1
2,3,1,3,"Heikkinen, Miss. Laina",female,26.000000,STON/O2. 3101282,7.9250,NaN,S,1
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.000000,113803,53.1000,C123,S,1
4,5,0,3,"Allen, Mr. William Henry",male,35.000000,373450,8.0500,NaN,S,1
5,6,0,3,"Moran, Mr. James",male,29.699118,330877,8.4583,NaN,Q,1
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.000000,17463,51.8625,E46,S,1
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.000000,349909,21.0750,NaN,S,0
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.000000,347742,11.1333,NaN,S,1
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.000000,237736,NaN,NaN,C,0

### Parting Fun Facts:

If you really like the resulting data frame you produced, and want to download it into a file to share with all your friends and family, you can do that! `to_csv()` or `to_excel()` allows you to save the dataframe locally.

Congrats on finishing your second assignment, see you next week!

____